name: surf_pose_eval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Core Python and essential packages
  - python=3.10 # Use Python 3.10 for better compatibility
  - numpy=1.24.3
  - scipy=1.11.1
  - pandas=2.0.3
  - pyyaml=6.0
  - tqdm=4.65.0

  # PyTorch ecosystem - use compatible versions
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8

  # Scientific computing and visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - ipykernel=6.24.0

  # Video and image processing - use pip versions to avoid conflicts
  - ffmpeg=6.0
  - imageio=2.31.1
  - imageio-ffmpeg=0.4.8

  # MLflow and experiment tracking
  - mlflow=2.5.0
  - optuna=3.2.0

  # Development tools
  - black=23.7.0
  - flake8=6.0.0
  - pytest=7.4.0

  # GPU monitoring
  - nvidia-ml-py=12.535.77

  # Install remaining packages via pip to avoid conflicts
  - pip=23.2.1
  - pip:
      # OpenCV via pip (avoids conda conflicts with jpeg libraries)
      - opencv-python==4.8.0.76

      # MMPose and MMDetection ecosystem
      - mmengine==0.8.4
      - mmcv==2.0.1
      - mmdet==3.1.0
      - mmpose==1.1.0
      - xtcocotools==1.14.1

      # MediaPipe (use stable version)
      - mediapipe==0.10.3

      # YOLOv8 (Ultralytics)
      - ultralytics==8.0.134

      # BlazePose (through MediaPipe)
      - protobuf==3.20.3

      # MMPose framework dependencies
      - timm==0.9.2

      # Video and image processing
      - decord==0.6.0
      - pillow==10.0.0

      # Additional utilities
      - rich==13.4.2
      - typer==0.9.0
      - wandb==0.15.8
      - tensorboard==2.13.0

      # Memory profiling
      - pympler==0.9
      - psutil==5.9.5

      # Configuration management
      - hydra-core==1.3.2
      - omegaconf==2.3.0

      # Pose-specific metrics
      - pose-evaluation==0.1.0

variables:
  # CUDA environment variables
  CUDA_VISIBLE_DEVICES: "0"
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"

  # MMPose model cache
  TORCH_HOME: "~/.cache/torch"
  MMPOSE_CACHE_DIR: "~/.cache/mmpose"
