name: surf_pose_eval
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python and essential packages
  - python=3.9
  - numpy=1.24.3
  - scipy=1.11.1
  - pandas=2.0.3
  - pyyaml=6.0
  - tqdm=4.65.0

  # PyTorch for Apple Silicon (CPU + Metal Performance Shaders)
  - pytorch::pytorch=2.0.1
  - pytorch::torchvision=0.15.2
  - pytorch::torchaudio=2.0.2

  # Scientific computing and visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - jupyter=1.0.0

  # Video and image processing (conda-forge versions work well on macOS)
  - ffmpeg=6.0
  - imageio=2.31.1

  # Development tools
  - pytest=7.4.0

  # Install remaining packages via pip to avoid conflicts
  - pip=23.2.1
  - pip:
      # OpenCV via pip (works better than conda on macOS)
      - opencv-python==4.8.0.76

      # MLflow and experiment tracking
      - mlflow==2.5.0
      - optuna==3.2.0

      # MediaPipe (use latest version - 0.10.21 confirmed working on Apple Silicon)
      - mediapipe==0.10.21

      # YOLOv8 (supports Apple Silicon MPS)
      - ultralytics==8.0.134

      # Memory profiling
      - psutil==5.9.5

      # Utilities
      - rich==13.4.2
      - pillow==10.0.0

    # MMPose can be installed later if needed
    # Note: Some MMPose components may have limited Apple Silicon support

variables:
  # Use Metal Performance Shaders for acceleration
  PYTORCH_ENABLE_MPS_FALLBACK: "1"
