name: surf_pose_eval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Core Python and system
  - python=3.10
  - pip
  - setuptools
  - wheel

  # PyTorch ecosystem (compatible versions for MMCV)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8

  # Core ML and scientific computing
  - numpy=1.24.3
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pillow=10.0.0

  # Media processing
  - imageio=2.31.1
  - imageio-ffmpeg=0.4.8

  # Code quality and testing
  - black=23.0
  - flake8=6.0
  - pytest=7.4.0
  - pytest-cov=4.1.0

  # Visualization
  - plotly=5.15.0

  # ML experiment tracking and optimization
  - mlflow=2.5.0
  - optuna=3.2.0
  - tensorboard=2.13.0

  # Basic dependencies
  - cython=0.29.36
  - pyyaml=6.0
  - requests=2.31.0
  - tqdm=4.65.0
  - terminaltables=3.1.10

  # Additional utilities
  - click=8.1.6
  - colorama=0.4.6
  - rich=13.4.2
  - typer=0.9.0

  # Pip dependencies - install these AFTER conda environment is created
  - pip:
      - opencv-python==4.8.0.76
      - mediapipe==0.10.14
      - ultralytics==8.0.165
      - psutil==5.9.5
      - xtcocotools==1.12
