name: surf_pose_eval
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python and system
  - python=3.10
  - pip
  - setuptools
  - wheel

  # CUDA and PyTorch ecosystem
  - pytorch
  - torchvision
  - torchaudio

  # Core ML and scientific computing - Match working SurfAnalysis approach
  - numpy>=1.24.3
  - scipy
  - scikit-learn
  - pandas
  - matplotlib

  - pillow

  # Media processing
  - imageio

  # Development and testing
  - pytest

  # ML experiment tracking and optimization
  - mlflow
  - optuna

  # Additional utilities
  - pyyaml
  - tqdm
  - rich

  # Pip dependencies for pose estimation packages
  - pip:
      # OpenCV
      - opencv-python>=4.7.0

      # MediaPipe for pose estimation
      - mediapipe>=0.10.0

      # YOLOv8 from Ultralytics
      - ultralytics>=8.0.0

      # OpenMMLab integration
      - openmim>=0.3.7

      # Additional utilities
      - termcolor
      - psutil

    # Note: MMPose installed via setup script after environment creation

# Environment variables for CUDA optimization
variables:
  CUDA_VISIBLE_DEVICES: "0" # Use first GPU by default
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:128" # Optimize memory allocation
