name: surf_pose_eval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Core Python and essential packages
  - python=3.9
  - numpy=1.24.3
  - scipy=1.11.1
  - pandas=2.0.3
  - pyyaml=6.0
  - tqdm=4.65.0

  # PyTorch ecosystem (install first to avoid conflicts)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8

  # Scientific computing and visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - jupyter=1.0.0

  # Video and image processing (conda-forge versions)
  - ffmpeg=6.0
  - imageio=2.31.1

  # Development tools
  - pytest=7.4.0

  # Install remaining packages via pip to avoid conflicts
  - pip=23.2.1
  - pip:
      # OpenCV via pip (avoids conda conflicts)
      - opencv-python==4.8.0.76

      # MLflow and experiment tracking
      - mlflow==2.5.0
      - optuna==3.2.0

      # MediaPipe (CPU-based, no conflicts)
      - mediapipe==0.10.3

      # YOLOv8
      - ultralytics==8.0.134

      # Memory profiling
      - psutil==5.9.5

      # Utilities
      - rich==13.4.2
      - pillow==10.0.0

    # Only install MMPose if you need it (comment out if causing issues)
    # - mmengine==0.8.4
    # - mmcv==2.0.1
    # - mmdet==3.1.0
    # - mmpose==1.1.0

variables:
  CUDA_VISIBLE_DEVICES: "0"
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"
