name: mmpose_build
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - tqdm
  - pytorch=2.1.*
  - torchvision=0.16.*
  - pytorch-cuda=12.1
  - gcc_linux-64=9.*
  - gxx_linux-64=9.*
  - scikit-learn
  - scipy
  - seaborn
  - pip:
      - opencv-python
      - pillow
      - pyyaml
      - fsspec
