# MediaPipe Pose Configuration
# Fast, edge-optimized pose estimation

model:
  name: "mediapipe"
  type: "2d_pose"
  description: "Google MediaPipe Pose - optimized for real-time mobile inference"

  # Model parameters
  parameters:
    model_complexity: 1 # 0: Lite, 1: Full, 2: Heavy
    min_detection_confidence: 0.2 # Lower threshold for better detection
    min_tracking_confidence: 0.2 # Lower threshold for better tracking
    smooth_landmarks: true
    enable_segmentation: false
    smooth_segmentation: true
    static_image_mode: false # Set to true for single images

  # Input preprocessing
  preprocessing:
    normalize: true
    target_size: [256, 256] # MediaPipe uses square inputs
    maintain_aspect_ratio: true
    interpolation: "bilinear"

  # Output format
  output:
    keypoint_format: "mediapipe_33" # 33 keypoints including face and hands
    coordinate_system: "normalized" # [0, 1] range
    confidence_included: true
    visibility_included: true

# Performance characteristics
performance:
  expected_fps: 30
  memory_usage_mb: 200
  edge_compatible: true
  real_time_capable: true

# Evaluation specific settings
evaluation:
  # Keypoint mapping to standard pose format (17 keypoints COCO format)
  keypoint_mapping:
    nose: 0
    left_eye: 2
    right_eye: 5
    left_ear: 7
    right_ear: 8
    left_shoulder: 11
    right_shoulder: 12
    left_elbow: 13
    right_elbow: 14
    left_wrist: 15
    right_wrist: 16
    left_hip: 23
    right_hip: 24
    left_knee: 25
    right_knee: 26
    left_ankle: 27
    right_ankle: 28

  # Quality thresholds for evaluation
  quality_thresholds:
    min_confidence: 0.3
    min_visibility: 0.5
    max_missing_keypoints: 5

# Optuna hyperparameter optimization ranges
optuna_search_space:
  model_complexity:
    type: "categorical"
    choices: [0, 1, 2]

  min_detection_confidence:
    type: "uniform"
    low: 0.1
    high: 0.9

  min_tracking_confidence:
    type: "uniform"
    low: 0.1
    high: 0.9

  smooth_landmarks:
    type: "categorical"
    choices: [true, false]

# Strengths and limitations for reporting
characteristics:
  strengths:
    - "Extremely fast inference suitable for mobile devices"
    - "Good temporal consistency with tracking"
    - "Robust in varying lighting conditions"
    - "No additional model downloads required"
    - "Built-in face and hand keypoints"

  limitations:
    - "Lower accuracy compared to research-grade models"
    - "Limited customization options"
    - "Normalized coordinates require rescaling"
    - "Single person detection only"
    - "May struggle with extreme poses"

  use_cases:
    - "Real-time mobile applications"
    - "Edge deployment scenarios"
    - "Quick prototyping and testing"
    - "Applications where speed > accuracy"
