model_name: "pytorch_pose"
model_class: "PyTorchPoseWrapper"

# PyTorch KeypointRCNN configuration
confidence_threshold: 0.7
keypoint_threshold: 0.3
nms_threshold: 0.3
max_detections: 10

# Optuna hyperparameter search space
optuna_params:
  confidence_threshold:
    type: "float"
    low: 0.5
    high: 0.9
    step: 0.05
  keypoint_threshold:
    type: "float"
    low: 0.1
    high: 0.6
    step: 0.1
  max_detections:
    type: "int"
    low: 5
    high: 20
    step: 5
