# Local Development Configuration for Surfing Pose Estimation
# This configuration uses local storage instead of shared storage

# Experiment metadata
experiment:
  name: "surf_pose_local_dev"
  description: "Local development testing with pose estimation models"
  version: "1.0"
  author: "Developer"

# Dataset configuration
dataset:
  base_data_path: "./data/SD_02_SURF_FOOTAGE_PREPT"
  video_clips:
    h264_path: "03_CLIPPED/h264"
    ffv1_path: "03_CLIPPED/ffv1"
  annotations:
    labels_path: "04_ANNOTATED/surf-manoeuvre-labels"
    sony_300_labels: "sony_300"
    sony_70_labels: "sony_70"
  splits:
    train_ratio: 0.70
    val_ratio: 0.15
    test_ratio: 0.15
    random_seed: 42

# Model configuration
models:
  enabled_models:
    - "mediapipe"
    - "yolov8_pose"
  default_settings:
    confidence_threshold: 0.3
    batch_size: 1
    device: "auto"
    half_precision: false

# Evaluation configuration
evaluation:
  quick_test:
    num_clips: 10 # Small for quick testing
    max_duration_seconds: 10
    cameras: ["SONY_300", "SONY_70"]
  comprehensive_test:
    num_clips: 50 # Moderate for local testing
    max_duration_seconds: 30
    cameras: ["SONY_300", "SONY_70"]
  metrics:
    pose_accuracy:
      - "pck_0.2"
    performance:
      - "inference_latency_ms"
      - "memory_usage_gb"
      - "throughput_fps"

# MLflow configuration
mlflow:
  enabled: true
  experiment_name: "surf_pose_local_dev"
  tracking_uri: "./results/mlruns"
  logging:
    parameters: true
    metrics: true
    artifacts: true
    models: false
    log_predictions: true
    log_visualizations: true
    max_videos_per_run: 2
  default_tags:
    project: "surf_pose_evaluation"
    stage: "development"
    platform: "local"

# Optuna configuration
optuna:
  enabled: false # Disabled for quick local testing
  n_trials: 5
  timeout_minutes: 15

# Hardware configuration
hardware:
  device:
    primary: "auto"
    fallback: "cpu"
  memory:
    max_memory_gb: 4
    cache_enabled: true
    clear_cache_frequency: 10

# Visualization and output - LOCAL STORAGE
output:
  # Results directory
  results_dir: "./results"

  # Visualization settings - LOCAL STORAGE EXAMPLE
  visualization:
    enabled: true
    save_overlay_videos: true
    save_keypoint_plots: true
    save_comparison_plots: true
    max_examples_per_model: 2 # Small for quick testing

    # LOCAL STORAGE: Omit shared_storage_path to use local results directory
    # shared_storage_path: null  # Explicitly disable shared storage

    # This will save visualizations to: ./results/visualizations/
    # Instead of the shared location

  # Report generation
  reports:
    generate_html_report: true
    generate_pdf_summary: false
    include_failure_analysis: true

# Logging configuration
logging:
  level: "DEBUG" # Verbose for development
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  save_to_file: true
  log_file: "./results/evaluation_local.log"

# Development and debugging
debug:
  enabled: true
  save_intermediate_results: true
  profile_memory: false
  profile_compute: false
  verbose_errors: true
