# Production Configuration for Surfing Pose Estimation
# This configuration uses lossless MKV format for production testing

# Experiment metadata
experiment:
  name: "surf_pose_production_test"
  description: "Production-quality testing with lossless video format"
  version: "1.0"
  author: "Production Team"

# Dataset configuration
dataset:
  base_data_path: "./data/SD_02_SURF_FOOTAGE_PREPT"
  video_clips:
    h264_path: "03_CLIPPED/h264"
    ffv1_path: "03_CLIPPED/ffv1"
    # Input video format for inference (use high quality for production)
    input_format: "ffv1" # Options: "h264", "ffv1"
  annotations:
    labels_path: "04_ANNOTATED/surf-manoeuvre-labels"
    sony_300_labels: "sony_300"
    sony_70_labels: "sony_70"
  splits:
    train_ratio: 0.70
    val_ratio: 0.15
    test_ratio: 0.15
    random_seed: 42

# Model configuration
models:
  enabled_models:
    - "mediapipe"
    - "blazepose"
    - "yolov8_pose"
    - "mmpose"
    - "pytorch_pose"
  default_settings:
    confidence_threshold: 0.3
    batch_size: 1
    device: "cuda"
    half_precision: false

# Evaluation configuration
evaluation:
  quick_test:
    num_clips: 20
    max_duration_seconds: 10
    cameras: ["SONY_300", "SONY_70"]
  comprehensive_test:
    num_clips: 200
    max_duration_seconds: 30
    cameras: ["SONY_300", "SONY_70"]
  metrics:
    pose_accuracy:
      - "pck_0.1"
      - "pck_0.2"
      - "pck_0.3"
      - "mpjpe"
    performance:
      - "inference_latency_ms"
      - "memory_usage_gb"
      - "throughput_fps"
      - "model_size_mb"

# MLflow configuration
mlflow:
  enabled: true
  experiment_name: "surf_pose_production"
  tracking_uri: "./results/mlruns"
  logging:
    parameters: true
    metrics: true
    artifacts: true
    models: false
    log_predictions: true
    log_visualizations: true
    max_videos_per_run: 5
  default_tags:
    project: "surf_pose_evaluation"
    stage: "production"
    dataset: "widemouth_march_2025"

# Optuna configuration
optuna:
  enabled: true
  study_name: "surf_pose_optimization_production"
  direction: "maximize"
  n_trials: 50
  timeout_minutes: 180

# Hardware configuration
hardware:
  gpu:
    device_id: 0
    memory_fraction: 0.9
    allow_growth: true
  cpu:
    num_workers: 8
    num_threads: 16
  memory:
    max_memory_gb: 32
    cache_enabled: true
    clear_cache_frequency: 50

# Visualization and output - PRODUCTION SETTINGS
output:
  results_dir: "./results"

  # Visualization settings - LOSSLESS FORMAT
  visualization:
    enabled: true
    save_overlay_videos: true
    save_keypoint_plots: true
    save_comparison_plots: true
    max_examples_per_model: 10

    # Shared storage for production
    shared_storage_path: "data/SD_02_SURF_FOOTAGE_PREPT/05_ANALYSED_DATA/POSE"

    encoding:
      format: "h264" # h264, h265, prores, ffv1, lossless
      quality:
        crf: 23 # 18-28 for good quality, lower = better quality
        preset: "fast" # ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
      pixel_format: "yuv420p"
      audio:
        enabled: true
        codec: "copy" # copy, aac, mp3
      container: "mp4" # mp4, mkv, avi, mov

    # PRODUCTION VIDEO ENCODING - LOSSLESS MKV
    # encoding:
    #   format: "lossless" # Lossless H.264 for production testing
    #   quality:
    #     crf: 0 # Lossless encoding
    #     preset: "veryslow" # Best compression efficiency
    #   pixel_format: "yuv444p" # Full chroma resolution
    #   audio:
    #     enabled: true
    #     codec: "copy" # Preserve original audio
    #   container: "mkv" # MKV container for lossless

  # Alternative encoding options for different use cases:
  #
  # For FFV1 lossless:
  # encoding:
  #   format: "ffv1"
  #   quality:
  #     level: 3
  #   pixel_format: "yuv420p"
  #   container: "mkv"
  #
  # For ProRes (macOS):
  # encoding:
  #   format: "prores"
  #   quality:
  #     profile: 2  # ProRes 422
  #   pixel_format: "yuv422p10le"
  #   container: "mov"

  # Report generation
  reports:
    generate_html_report: true
    generate_pdf_summary: true
    include_failure_analysis: true

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  save_to_file: true
  log_file: "./results/evaluation_production.log"

# Development and debugging
debug:
  enabled: false
  save_intermediate_results: false
  profile_memory: true
  profile_compute: true
  verbose_errors: true
